"""Build products.js from products.xlsx.

Usage (in the project folder, next to index.html):
    pip install openpyxl        (first time only)
    python build_products.py

Edit products.xlsx in Excel, save, close it, then run the command above.
It rewrites products.js and prints warnings for anything that looks wrong.
Never edit products.js by hand: your changes would be overwritten.
"""
import json, re, sys
from pathlib import Path
from openpyxl import load_workbook

ROOT = Path(__file__).parent
SIZE_OK = re.compile(r"^(XXS|XS|S|M|L|XL|XXL|3XL|4XL|One Size|Free Size|\d{1,2}|\d{1,2}Y|\d{1,2}M|\d{1,2}-\d{1,2}[YM])$")
warn = []

def split(v):
    parts = re.split(r"[,\n;،]+", str(v or ""))
    out = []
    for p in (x.strip() for x in parts):
        if p and p not in out:
            out.append(p)
    return out

def title(c):
    return re.sub(r"(^|[\s+*/-])(\w)", lambda m: m.group(1) + m.group(2).upper(), c.lower())

def main():
    path = ROOT / "products.xlsx"
    if not path.exists():
        sys.exit("products.xlsx not found next to this script.")
    wb = load_workbook(path, data_only=True)
    cats, order = {}, []
    for r in wb["Sections"].iter_rows(min_row=2, values_only=True):
        if not r or not r[0]:
            continue
        key = str(r[0]).strip()
        order.append(key)
        cats[key] = {"en": str(r[1] or key), "ar": str(r[2] or key), "count": 0,
                     "price": int(r[5] or 0), "sizes": split(r[3]), "colors": split(r[4])}
    ov, seen = {}, {}
    for i, r in enumerate(wb["Products"].iter_rows(min_row=2, values_only=True), start=2):
        if not r or not r[0]:
            continue
        sec, n = str(r[0]).strip(), r[1]
        where = f"row {i} ({sec} {n})"
        if sec not in cats:
            warn.append(f"{where}: unknown section, skipped"); continue
        try:
            n = int(n)
        except (TypeError, ValueError):
            warn.append(f"{where}: 'No' must be a number, skipped"); continue
        if (sec, n) in seen:
            warn.append(f"{where}: duplicate number, skipped"); continue
        seen[(sec, n)] = True
        name = str(r[2] or "").strip()
        price = r[3] if isinstance(r[3], (int, float)) else 0
        sizes = split(r[4])
        colors = []
        for c in split(r[5]):
            c = title(c)
            if c not in colors:
                colors.append(c)
        status = str(r[6] or "").strip().lower()
        desc = str(r[7] or "").strip()
        if not name: warn.append(f"{where}: empty name")
        if not price: warn.append(f"{where}: no price (will show 'Ask for price')")
        for s in sizes:
            if not SIZE_OK.match(s): warn.append(f"{where}: unusual size '{s}'")
        for c in colors:
            if re.search(r"this|color|size", c, re.I): warn.append(f"{where}: unusual color '{c}'")
        if len(name) > 50: warn.append(f"{where}: name is long ({len(name)} chars), keep it short")
        o = {"name": name, "price": int(price), "sizes": sizes, "colors": colors}
        if desc: o["desc"] = desc
        if status == "sold out": o["soldOut"] = True
        elif status == "hidden": o["hidden"] = True
        elif status: warn.append(f"{where}: unknown status '{status}' (use: sold out / hidden)")
        ov[f"{sec}-{n}"] = o
        cats[sec]["count"] = max(cats[sec]["count"], n)
    for sec in order:                                   # gaps in numbering
        for n in range(1, cats[sec]["count"] + 1):
            if (sec, n) not in seen:
                ov[f"{sec}-{n}"] = {"name": "", "price": 0, "sizes": [], "colors": [], "hidden": True}
                warn.append(f"{sec} {n}: missing row, hidden automatically")
    out = ["// AUTO-GENERATED by build_products.py from products.xlsx. Do not edit by hand.",
           "const CATEGORIES = {"]
    out += [f'  {json.dumps(k)}: {json.dumps(cats[k], ensure_ascii=False)},' for k in order]
    out += ["};", "const OVERRIDES = {"]
    out += [f'  {json.dumps(k)}: {json.dumps(v, ensure_ascii=False)},' for k, v in ov.items()]
    out += ["};", ""]
    (ROOT / "products.js").write_text("\n".join(out), encoding="utf-8")
    print(f"products.js written: {len(ov)} products in {len(order)} sections.")
    if warn:
        print(f"\n{len(warn)} thing(s) to check:")
        for w in warn: print(" -", w)
    else:
        print("No warnings.")

if __name__ == "__main__":
    main()
